### PR TITLE
[WIP] feat: add MDX support

### PR DESCRIPTION
**Pull request by jlengstorf**
This PR supersedes #48.

Adds MDX support for pages and blogs. This is still a work in progress, but it’s functional right now.

### TODO

- [x] Refactor `SEO` component to use MDX instead of Remark
- [x] Add SEO back to pages
- [x] Add SEO back to posts
- [ ] Look into `Warning: Received `true` for a non-boolean attribute `title`.` error (I think it's from `gatsby-remark-images`)
- [ ] Look into `scrollLeft.js:13 GET data:image/jpeg net::ERR_INVALID_URL`

### CODE REVIEW

**Comment by jlengstorf** [comment]
A few things to mention here:

1. The "`true` for non-boolean attribute" error only happens in development, and seems to be something between MDX and Remark that's not actually breaking things, but causing warnings.
2. The `scrollLeft.js` issue is apparently happening because the base64 encoded image isn't being added, so it becomes a junk base64 URL. I have no idea _where_ this is coming from. @ChristopherBiscardi maybe you've seen this one?

Neither of these seems like a good enough reason to delay putting this into production and seeing how things go. #yolo

**Comment by ChristopherBiscardi** [comment]
> The "true for non-boolean attribute" error only happens in development, and seems to be something between MDX and Remark that's not actually breaking things, but causing warnings.

I believe this is due to a prop from gatsby-remark-images being passed down to the dom jsx element, which react will warn on but not break for. I made major changes to the internals for how the gatsby-remark plugins are handled (I removed a semi-buggy html-to-jsx plugin that was the previous approach for the plugins) in the next version (`gatsby-mdx@ci` if you wanted to try it) so ignoring this issue in the current stable release.

> scrollLeft.js

I've [seen this](https://github.com/ChristopherBiscardi/gatsby-mdx/issues/153#issuecomment-435022466) but haven't had a chance to dive into *why* it's happening (and until now, I didn't have a repro case for it). react-bootstrap/dom-helpers is a @jquense lib, so maybe they have some insight? I don't see anything operating on image urls specifically in [the source](https://github.com/react-bootstrap/dom-helpers/blob/01d5f8ae8fa322a0d06c541b0cc961c1b463c4ca/src/query/scrollLeft.js) for scrollLeft.

**Comment by jlengstorf** [comment]
I have a theory that this is something related to `gatsby-image` and the viewport detection. However, I have no proof and haven't dug too deep here. What I _do_ know is that on e.g. [this page](https://lengstorf.com/level-setting), the markup that's generated includes this:

```html
<span
  class="gatsby-resp-image-background-image"
  style="padding-bottom: 44.375%; position: relative; bottom: 0px; left: 0px; background-image: url(&quot;data:image/jpeg&quot;); background-size: cover; display: block; transition: opacity 0.5s ease 0.5s; opacity: 0;"
></span>
```

Specifically, the `background-image: url(&quot;data:image/jpeg&quot;);` is concerning. I'm not sure where to look, but maybe it's a case of an empty value where the code doesn't expect one to be possible, with gives us the empty `data:image/jpeg`. Not sure how those quotes end up escaped, though.

**Comment by ChristopherBiscardi** [comment]
That's very likely the buggy html-to-jsx plugin we used to use in gatsby-mdx. The new approach is to make gatsby-remark-* plugins insert HAST into the AST instead of chunks of html strings so that additional processing happens "as expected".

**Pull request merged**
