### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
- Update dependencies
- Use [`gatsby-remark-embedder`](https://github.com/MichaelDeBoey/gatsby-remark-embedder) for embedding SoundCloud/Twitter/YouTube

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
Blocked by https://github.com/jlengstorf/gatsby-theme-jason-blog/pull/18

**Comment by jlengstorf** [comment]
holding off on this until https://github.com/gatsbyjs/gatsby/issues/20150 has a resolution — if relative imports are broken in MDX, that'll break my whole site

**Comment by MichaelDeBoey** [comment]
Ping @jlengstorf

**Comment by jlengstorf** [comment]
I've got some changes happening elsewhere that will make this branch hard to merge — I'm going to close it

the updated deps will ship soon

**Comment by MichaelDeBoey** [comment]
I’ll resubmit the gatsby-remark-embedder changes then 🙂

**Pull request closed without merging**
